/*
 * PVPC schema
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"os"
	"time"
	_ "time/tzdata"

	sw "github.com/AigisCorp/redata-api-consumer/app/go"
	log "github.com/sirupsen/logrus"
)

func init() {
	// setup logrus
	log.SetOutput(os.Stdout)
	log.SetLevel(log.DebugLevel)
	log.SetFormatter(&log.JSONFormatter{})
}

func main() {
	location, err := time.LoadLocation(os.Getenv("location"))
	if err != nil {
		log.Fatal("Error loading location: %v", err)
	}
	time.Local = location

	routes := sw.ApiHandleFunctions{}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
