// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/Charge
type Charge struct {
	Charge bool `json:"charge"`
}

// GetCharge returns the value of Charge.
func (s *Charge) GetCharge() bool {
	return s.Charge
}

// SetCharge sets the value of Charge.
func (s *Charge) SetCharge(val bool) {
	s.Charge = val
}

func (*Charge) chargeRes() {}

// ChargeNotFound is response for Charge operation.
type ChargeNotFound struct{}

func (*ChargeNotFound) chargeRes() {}

// GetCheapNotFound is response for GetCheap operation.
type GetCheapNotFound struct{}

func (*GetCheapNotFound) getCheapRes() {}

// GetCheapestNotFound is response for GetCheapest operation.
type GetCheapestNotFound struct{}

func (*GetCheapestNotFound) getCheapestRes() {}

// Ref: #/components/schemas/Price
type Price struct {
	Price    float64 `json:"price"`
	Datetime string  `json:"datetime"`
}

// GetPrice returns the value of Price.
func (s *Price) GetPrice() float64 {
	return s.Price
}

// GetDatetime returns the value of Datetime.
func (s *Price) GetDatetime() string {
	return s.Datetime
}

// SetPrice sets the value of Price.
func (s *Price) SetPrice(val float64) {
	s.Price = val
}

// SetDatetime sets the value of Datetime.
func (s *Price) SetDatetime(val string) {
	s.Datetime = val
}

func (*Price) getCheapestRes() {}

// Ref: #/components/schemas/Prices
type Prices map[string]jx.Raw

func (s *Prices) init() Prices {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

func (*Prices) getCheapRes() {}
